<?php
/**
 * @author Rafael Corrêa Gomes <rafaelcgstz@gmail.com>
 * @copyright Copyright (c) 2023.
 */
/** @var $block \Rafaelcg\Quicklink\Block\QuickLink */
/** @var $viewModel \Rafaelcg\Quicklink\ViewModel\QuickLink */
$viewModel = $block->getViewModel();
?>
<!-- Google Quicklink -->
<script>
    require(['jquery', 'quicklink', 'polyfillio', 'domReady!'], function($, quicklink) {
        quicklink.listen({
            <?= $block->escapeHtml($viewModel->getTimeout());
            echo $block->escapeHtml($viewModel->getLimit());
            echo $block->escapeHtml($viewModel->getConcurrencyLimit());
            echo $block->escapeHtml($viewModel->getPriority()); ?>
            ignores: [
                /\/api\/?/,
                uri => uri.includes('#'),
                uri => uri.includes('account'),
                uri => uri.includes('catalogsearch'),
                uri => uri.includes('checkout'),
                uri => uri.includes('logout'),
                (uri, elem) => elem.hasAttribute('noprefetch')
            ]
        });
    });
</script>
