<?php
/**
 * @author Rafael Corrêa Gomes <rafaelcgstz@gmail.com>
 *  @copyright Copyright (c) 2018
 *  @license https://opensource.org/licenses/OSL-3.0.php Open Software License 3.0
 */

?>
<?php /** @var $this \Rafaelcg\QuickLink\Block\QuickLink */ ?>
<!-- BEGIN Google QuickLink -->
<script type="text/x-magento-init">
{
    "*": {
        "Rafaelcg_QuickLink/js/quicklink": <?= $this->initConfig() ?>
    }
}
</script>
<!-- END Google QuickLink -->
