---
    version: "2"
    checks:
      argument-count:
        enabled: true
        config:
          threshold: 4
          languages:
            - javascript
            - php
      complex-logic:
        enabled: true
        config:
          threshold: 4
          languages:
            - javascript
            - php
      file-lines:
        enabled: true
        config:
          threshold: 250
          languages:
            - javascript
            - php
      method-complexity:
        enabled: true
        config:
          threshold: 5
          languages:
            - javascript
            - php
      method-count:
        enabled: true
        config:
          threshold: 10
          languages:
            - javascript
            - php
      method-lines:
        enabled: true
        config:
          threshold: 40
          languages:
            - javascript
            - php
      nested-control-flow:
        enabled: true
        config:
          threshold: 4
          languages:
            - javascript
            - php
      return-statements:
        enabled: true
        config:
          threshold: 2
          languages:
            - javascript
            - php
      similar-code:
        enabled: true
        config:
          threshold: 60
          languages:
            - javascript
            - php
      identical-code:
        enabled: true
        config:
          threshold: 40
          languages:
            - javascript
            - php
    plugins:
      eslint:
        enabled: true
      fixme:
        enabled: true
      phan:
        enabled: true
        config:
          file_extensions: php
          ignore-undeclared: true
    exclude_patterns:
      - "*/Test"
      - "*/Setup/*Setup.php"
      - "vendor/*"
      - "Resources/*"
