sudo: required
dist: xenial

services:
  - elasticsearch
  - mysql

language: php

jobs:
  include:
    - php: 7.4
      env:
        - MAGENTO_VERSION=2.4.3 MAGENTO_EDITION=community ES_VERSION=7.16-amd64
    - if: type != pull_request
      php: 7.4
      env:
        - MAGENTO_VERSION=2.4.3 MAGENTO_EDITION=enterprise ES_VERSION=7.16-amd64
    - php: 8.1
      env:
          - MAGENTO_VERSION=2.4.5 MAGENTO_EDITION=community ES_VERSION=7.17-amd64
    - if: type != pull_request
      php: 8.1
      env:
          - MAGENTO_VERSION=2.4.5 MAGENTO_EDITION=enterprise ES_VERSION=7.17-amd64

before_install:
  - sudo service elasticsearch stop
  - export ES_HOME=/usr/share/elasticsearch
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-$ES_VERSION.deb
  - sudo dpkg -i --force-confnew elasticsearch-$ES_VERSION.deb
  - sudo chgrp elasticsearch /etc/default/elasticsearch -R
  - sudo service elasticsearch start
  - sleep 5
  - composer self-update --1
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then composer config -g http-basic.repo.magento.com $MAGENTO_USERNAME $MAGENTO_PASSWORD ; fi
  - echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > auth.json
  - if [ -n "$GH_ACCESS_TOKEN" ]; then composer config github-oauth.github.com ${GH_ACCESS_TOKEN}; fi;
  - composer global require hirak/prestissimo
  - chmod +x ./bin/*
  - ./bin/prepare_php.sh
  - ./bin/prepare_apache.sh
  - ./bin/before_install.sh

install:
  - composer install --prefer-dist

cache:
  directories:
    - $HOME/.composer/cache

script:
  - ./bin/test_magento.sh
  - vendor/bin/phpcs --config-set installed_paths ../../magento/magento-coding-standard/
  - vendor/bin/phpcs --standard=Magento2 --severity=9 --ignore='.git,vendor' ./
