<?php
/**
 * @author Rafael Corrêa Gomes <rafaelcgstz@gmail.com>
 * @copyright Copyright (c) 2019.
 */
/** @var $block \Rafaelcg\Quicklink\Block\QuickLink */
/** @var $viewModel \Rafaelcg\Quicklink\ViewModel\QuickLink */
$viewModel = $block->getViewModel();
?>
<!-- Google Quicklink -->
<script defer>
    require(['jquery', 'quicklink', 'polyfillio', 'domReady!'], function($, quicklink) {
        quicklink.listen({
            <?= $block->escapeHtml($viewModel->getTimeout()) ?>
            <?= $block->escapeHtml($viewModel->getLimit()) ?>
            <?= $block->escapeHtml($viewModel->getConcurrencyLimit()) ?>
            <?= $block->escapeHtml($viewModel->getPriority()) ?>
            ignores: [
                /\/api\/?/,
                uri => uri.includes('#'),
                uri => uri.includes('logout'),
                uri => uri.includes('account'),
                uri => uri.includes('checkout'),
                (uri, elem) => elem.hasAttribute('noprefetch')
            ]
        });
    });
</script>
